a = int(input("Enter value"))
b = int(input("Enter value"))
c = int(input("Enter value"))
d = int(input("Enter value"))
e = int(input("Enter value"))
f = int(input("Enter value"))
g = int(input("Enter value"))
h = a+b+c+d+e+f+g
print(h)
print("I have updated the sum of numbers")
